version: '3'

services:
  app:
    build: .
    restart: always
    env_file:
    - .config
    depends_on:
    - db
    ports:
    - "6868:6868"
    networks:
    - nginx-proxy
    - app

  db:
    image: mongo:4.1
    restart: always
    networks:
    - app
    volumes:
    - ./volumes/db:/data/db
    environment:
    - MONGO_INITDB_DATABASE=testdb

networks:
  app:
  nginx-proxy:
    external: true